name: github-actions
run-name: GitHub Actions
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: app install
        working-directory: ./app
        run: npm install
        if: always()
      - name: app build
        working-directory: ./app
        run: npm run build
        if: always()
      - name: app unit test
        working-directory: ./app
        run: npm run test:unit
        if: always()
      - name: app build storybook
        working-directory: ./app
        run: npm run test:build-storybook
        if: always()
      - name: app approve
        working-directory: ./app
        run: npm run loki:approve
        if: always()
      - name: app screenshot testing
        working-directory: ./app
        run: npm run test:ui:ci
        if: always()
      - name: shared install
        working-directory: ./api
        run: npm install
        if: always()
      - name: shared build
        working-directory: ./api
        run: npm run build
        if: always()
