name: github-actions
run-name: GitHub Actions
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: app install
        working-directory: ./app
        run: npm install
      - name: app build
        working-directory: ./app
        run: npm run build
      - name: app unit test
        working-directory: ./app
        run: npm run test:unit
      - name: app build storybook
        working-directory: ./app
        run: npm run test:build-storybook
      - name: app screenshot testing
        working-directory: ./app
        run: npm run test:ui:ci
      - name: api install
        working-directory: ./api
        run: npm install
      - name: api build
        working-directory: ./api
        run: npm run build